const MAX_EVENT = 1024*1024;
export class ProtocolError extends Error { constructor(message){super(message);this.name='ProtocolError';this.code='stream_incomplete';} }
export function *parseSSE(input) {
  const text = typeof input==='string' ? input : new TextDecoder().decode(input);
  let data=[]; let eventType=null;
  const dispatch=()=>{ if(!data.length)return null; const value=data.join('\n'); data=[]; eventType=null; return value; };
  for(const line of text.replace(/^\ufeff/,'').split(/\r\n|\n|\r/)) { if(line==='') { const x=dispatch(); if(x!==null) yield x; continue; } if(line.startsWith(':')) continue; const i=line.indexOf(':'); const field=i<0?line:line.slice(0,i); const value=i<0?'':line.slice(i+1).replace(/^ /,''); if(field==='data'){data.push(value);if(data.join('\n').length>MAX_EVENT)throw new ProtocolError('event too large');} else if(field==='event') eventType=value; }
  const x=dispatch(); if(x!==null) yield x;
}
async function *frames(stream) { const decoder=new TextDecoder(); let carry=''; for await(const chunk of stream){ carry+=decoder.decode(chunk,{stream:true}); const lines=carry.split(/\r\n|\n|\r/); carry=lines.pop(); for(const line of lines) yield line; } carry+=decoder.decode(); if(carry) yield carry; }
export class ResponsesClient {
  constructor(config){ if(!config?.url||!config.model) throw new TypeError('responses url and model required'); this.url=config.url;this.model=config.model;this.fetch=config.fetch??fetch;this.accessToken=config.accessToken;this.headers=config.headers??{}; }
  async *respond({input,instructions='Complete the task using only declared tools.',tools=[],signal,runId='run'}={}) { const body={model:this.model,instructions,input,store:false,stream:true}; if(tools.length){body.tools=tools;body.tool_choice='auto';body.parallel_tool_calls=false;} const r=await this.fetch(this.url,{method:'POST',redirect:'error',signal,headers:{authorization:`Bearer ${this.accessToken}`,'content-type':'application/json',accept:'text/event-stream',originator:'yoloharness',session_id:runId,'x-client-request-id':runId.slice(0,64),...this.headers},body:JSON.stringify(body)}); if(!r.ok) throw Object.assign(new Error(`responses request failed (${r.status})`),{code:r.status===429?'rate_limited':'provider_error',status:r.status}); if(!r.body) throw new ProtocolError('missing response stream'); const calls=new Map(); let terminal=false; let text=''; for await(const line of frames(r.body)){ if(!line.trim()||line.startsWith(':'))continue; if(!line.startsWith('data:'))continue; const raw=line.slice(5).replace(/^ /,''); if(raw==='[DONE]')continue; let e; try{e=JSON.parse(raw)}catch{throw new ProtocolError('malformed event JSON')} const type=e.type; if(type==='response.output_text.delta'){text+=String(e.delta??'');yield {type:'text_delta',delta:String(e.delta??'')};} else if(type==='response.output_item.added'&&e.item?.type==='function_call'){calls.set(e.item.id,{...e.item,arguments:e.item.arguments??''});} else if(type==='response.function_call_arguments.delta'){const c=calls.get(e.item_id);if(c)c.arguments+=String(e.delta??'');} else if(type==='response.output_item.done'&&e.item?.type==='function_call'){const c=calls.get(e.item.id); const call={...e.item,arguments:e.item.arguments??c?.arguments??''}; if(c?.done && JSON.stringify(c.done)!==JSON.stringify(call))throw new ProtocolError('conflicting duplicate tool call'); if(!c?.done){c.done=call;yield {type:'tool_call',call:{id:call.id,call_id:call.call_id,name:call.name,arguments:call.arguments}};} } else if(type==='response.completed'){terminal=true;yield {type:'completed',status:e.response?.status??'completed',responseId:e.response?.id,text};} else if(type==='response.incomplete'||type==='response.failed'||type==='error'){yield {type:'failed',status:type==='response.incomplete'?'incomplete':'failed',error:String(e.error?.message??e.message??type),text}; return;} }
    if(!terminal) throw new ProtocolError('stream ended without completed response'); }
}
