import { createHash } from 'node:crypto';
import { constants as fsConstants } from 'node:fs';
import { lstat, mkdir, open, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';

export const MANIFEST = '.yoloharness-workspace-manifest.json';
const HARNESS_PREFIX = '.yolo';
function normalizeExclusions(names = []) { if (!Array.isArray(names) || names.some(name => typeof name !== 'string' || !name || name.includes('/') || name === '.' || name === '..')) throw new TypeError('invalid dependency directory names'); return new Set(names); }
function ignored(name, key, exclusions) { return name === MANIFEST || key === HARNESS_PREFIX || key.startsWith(`${HARNESS_PREFIX}/`) || exclusions.has(name); }
function ensureRelative(key) { if (!key || key.startsWith('/') || key.split('/').some(part => !part || part === '.' || part === '..')) throw new Error(`unsafe publication path: ${key}`); }
async function ownerSafe(path) { const info = await lstat(path); if (info.uid !== undefined && info.uid !== process.getuid?.() && info.uid !== 0) throw new Error(`unsafe publication ownership: ${path}`); if (info.isFile() && info.nlink > 1) throw new Error(`unsupported hardlink publication entry: ${path}`); if (info.isSymbolicLink() || info.isBlockDevice() || info.isCharacterDevice() || info.isFIFO() || info.isSocket()) throw new Error(`unsafe publication entry type: ${path}`); return info; }
async function digest(path) { const info = await ownerSafe(path); if (info.isFile()) return `file:${createHash('sha256').update(await readFile(path)).digest('hex')}`; if (info.isDirectory()) { const hash = createHash('sha256'); for (const name of (await readdir(path)).sort()) hash.update(name).update(await digest(join(path, name))); return `dir:${hash.digest('hex')}`; } throw new Error(`unsupported publication entry: ${path}`); }
async function walk(root, exclusions, current = root, result = []) { for (const name of (await readdir(current)).sort()) { const key = relative(root, join(current, name)).split('\\').join('/'); if (ignored(name, key, exclusions)) continue; ensureRelative(key); const path = join(current, name); const info = await ownerSafe(path); result.push({ key, path, info }); if (info.isDirectory()) await walk(root, exclusions, path, result); } return result; }

export async function validateEmptyWorkspace(workspace = process.cwd()) { const absolute = resolve(workspace); const info = await lstat(absolute).catch(() => null); if (!info?.isDirectory() || info.isSymbolicLink()) throw new TypeError('workspace must be a real directory'); if ((await readdir(absolute)).length !== 0) throw new Error('workspace must be initially empty; choose a fresh disposable directory'); return absolute; }

export async function seedWorkspace(source, staged, dependencyNames = [], baselinePath = join(staged, MANIFEST)) { const exclusions = normalizeExclusions(dependencyNames); await rm(staged, { recursive: true, force: true }); await mkdir(staged, { recursive: true, mode: 0o700 }); const entries = await walk(source, exclusions); for (const entry of entries) { const target = join(staged, entry.key); if (entry.info.isDirectory()) await mkdir(target, { recursive: true, mode: entry.info.mode & 0o777 }); else { await mkdir(dirname(target), { recursive: true, mode: 0o700 }); const fh = await open(target, fsConstants.O_WRONLY | fsConstants.O_CREAT | fsConstants.O_EXCL, entry.info.mode & 0o777); try { await fh.writeFile(await readFile(entry.path)); } finally { await fh.close(); } } } await writeFile(baselinePath, JSON.stringify({ version: 2, entries: Object.fromEntries(entries.map(entry => [entry.key, entry.info.isFile() ? 'file' : 'directory'])) }) + '\n', { mode: 0o600 }); }

async function destinationCheck(destination, key) { const parts = key.split('/'); let current = destination; for (const part of parts) { current = join(current, part); const existing = await lstat(current).catch(() => null); if (!existing) continue; const info = await ownerSafe(current); if (!info.isDirectory() || current === join(destination, key)) throw new Error(`publication conflict: ${key}`); } }
export async function publishWorkspace(staged, destination, dependencyNames = []) { const exclusions = normalizeExclusions(dependencyNames); const names = await readdir(destination); if (names.some(name => name !== HARNESS_PREFIX)) throw new Error('publication destination is not empty'); const entries = await walk(staged, exclusions); let created = 0; try { for (const entry of entries) { await destinationCheck(destination, entry.key); const target = join(destination, entry.key); if (entry.info.isDirectory()) { await mkdir(target, { mode: entry.info.mode & 0o777 }); created += 1; continue; } await mkdir(dirname(target), { recursive: true, mode: 0o700 }); const fh = await open(target, fsConstants.O_WRONLY | fsConstants.O_CREAT | fsConstants.O_EXCL, entry.info.mode & 0o777); try { await fh.writeFile(await readFile(entry.path)); await fh.sync(); } finally { await fh.close(); } created += 1; } return { version: 1, published: true, created }; } catch (error) { throw Object.assign(new Error(`publication_incomplete: ${error.message}; inspect or delete the generated directory before retrying`), { code: 'publication_incomplete', created }); } }
